Repository meltano/meltano, pull requests merged in 2022-06, with the labels that each got.

#6098 Update invoke to fire start event later
  src/meltano/cli/invoke.py
Labels: kind::bug

#6108 Add telemetry to `add` command
  src/meltano/cli/add.py
Labels: telemetry

#6109 Add telemetry to `install` command
  src/meltano/cli/install.py
Labels: telemetry

#6125 Warn about breaking changes for orchestrators dependent on schedule listings
  docs/src/_reference/v2-migration.md
Labels: v2.0

#6174 Fix defect where `pipeline-schedules` endpoint returned 500 error
  src/meltano/api/controllers/orchestrations.py
Labels: kind::bug, valuestream::meltano

#6268 ci: Use `docker run` instead of `services`
  .github/workflows/test.yml
Labels: ci/cd

#6276 fix(plugins): Replace deprecated `distutils.version.StrictVersion`
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  src/meltano/core/plugin/airflow.py
Labels: valuestream/Meltano
