Repository meltano/meltano, pull requests merged in 2022-07, with the labels that each got.

#6347 docs: Document current Docker image default Python version is 3.9
  docs/src/_guide/installation.md
Labels: Documentation

#6346 ci: Add missing poetry install step for building artifacts
  .github/workflows/build.yml
Labels: CI/CD

#6424 ci: Update version bump workflow to automate changelog generation
  .github/workflows/version_bump.yml
  pyproject.toml
Labels: CI/CD, valuestream/Meltano

#6411 docs: Document overriding capabilities and extending settings
  CHANGELOG.md
  docs/src/_guide/configuration.md
Labels: Documentation

#6343 chore: Remove unused CI config/workflow files
  .bumpversion.cfg
Labels: CI/CD

#6456 docs: Update for Windows and for using pipx --python version
  docs/getting-started.md
Labels: Community-Contributed PR

#6433 fix: Validating Mapper and Mappings names and alerting if necessary
  src/meltano/core/block/parser.py
  tests/meltano/cli/test_run.py
Labels: Community-Contributed PR
