Repository meltano/meltano, pull requests merged in 2022-10, with the labels that each got.

#6703 docs: update custom extractor tutorial
  docs/src/_tutorials/custom-extractor.md
Labels: Community-Contributed PR

#6751 fix: catch ConnectionError in /version endpoint
  src/meltano/api/controllers/root.py
Labels: Community-Contributed PR

#6814 feat: Support `meltano init` into an empty directory
  docs/src/_contribute/api.md
  docs/src/_contribute/prerequisites.md
  docs/src/_contribute/ui.md
  docs/src/_getting-started/index.md
  docs/src/_reference/command-line-interface.md
  src/meltano/cli/initialize.py
  src/meltano/cli/params.py
  src/meltano/core/project_init_service.py
  tests/meltano/cli/test_initialize.py
  tests/meltano/core/test_project_init_service.py
Labels: Community-Contributed PR

#6468 fix: symbolic link creation for meltano.exe when on windows
  src/meltano/core/project.py
Labels: Community-Contributed PR, Windows, kind/Bug, valuestream/Meltano

#6628 feat: Make `.meltano` folder path configurable via new `MELTANO_SYS_DIR_ROOT` env var
  docs/src/_concepts/environments.md
  docs/src/_concepts/project.md
  docs/src/_reference/settings.md
  src/meltano/core/bundle/settings.yml
  src/meltano/core/project.py
  src/meltano/core/project_init_service.py
Labels: Community-Contributed PR, kind/Feature, valuestream/Meltano
