Repository meltano/meltano, pull requests merged in 2024-12, with the labels that each got.

#8961 docs: Change to code theme that does not italicize keywords or variables
  docs/docusaurus.config.js
Labels: Community-Contributed PR, javascript

#8951 feat(cli): Add a simple log formatter that only contains the event by default
  docs/docs/guide/logging.md
  src/meltano/core/logging/__init__.py
  src/meltano/core/logging/formatters.py
  tests/meltano/core/logging/test_formatters.py
Labels: Logging

#8983 docs: Use a different repo in part 1 of Getting Started guide
  docs/docs/getting-started/part1.mdx
Labels: Documentation
