Repository meltano/meltano, pull requests merged in 2025-08, with the labels that each got.

#9425 packaging: Disallow click 8.2.2
  pyproject.toml
  uv.lock
Labels: cli, dependencies

#9426 packaging: Allow boto 1.40.x
  pyproject.toml
  uv.lock
Labels: dependencies, State Management

#9435 fix(deps): Disallow uv 0.8.7 since `find_uv` is broken on Python 3.9
  pyproject.toml
  uv.lock
Labels: installation, dependencies

#9450 feat: Add `--clear` option to select command
  docs/docs/reference/command-line-interface.md
  src/meltano/cli/select_entities.py
  src/meltano/core/select_service.py
  tests/meltano/cli/test_select.py
  tests/meltano/core/test_select_service.py
Labels: kind/Feature

#9456 fix: Honor `disable_tracking` setting
  src/meltano/core/tracking/tracker.py
Labels: kind/Bug, Telemetry, Settings

#9455 docs: Sync Meltano core settings
  docs/docs/reference/settings.mdx
Labels: Documentation, Settings

#9183 feat: Support custom `.env` paths
  docs/docs/reference/command-line-interface.md
  src/meltano/cli/cli.py
  src/meltano/core/project.py
  tests/meltano/cli/test_cli.py
Labels: Settings

#9412 feat: Add meltano logs command for viewing job logs
  docs/docs/guide/logging.md
  docs/docs/reference/command-line-interface.md
  pyproject.toml
  src/meltano/cli/__init__.py
  src/meltano/cli/logs.py
  src/meltano/core/db.py
  tests/meltano/cli/test_logs.py
Labels: Logging
