Repository meltano/meltano, pull requests merged in 2025-07, with the labels that each got.

#9344 feat: Log execution time at the end of a `meltano run` invocation
  docs/docs/getting-started/part1.mdx
  docs/docs/getting-started/part2.mdx
  docs/docs/getting-started/part3.mdx
  integration/example-library/meltano-run/index.md
  integration/meltano-run/validate.sh
  src/meltano/cli/run.py
  tests/meltano/cli/test_run.py
Labels: cli

#9346 test: Fix flaky `meltano compile` test that checks for some events in the logs
  tests/meltano/cli/test_compile.py
Labels: CI/CD, kind/Tech Debt

#9347 feat: Limit the traceback in console logs format to two frames
  docs/docs/guide/logging.md
  src/meltano/core/logging/formatters.py
  src/meltano/core/logging/utils.py
  tests/meltano/core/logging/test_formatters.py
Labels: OKR: New User Experience, Logging

#9350 feat: `meltano remove` no longer requires specifying a plugin type, i.e. `meltano remove tap-github` works too
  docs/docs/guide/plugin-management.md
  docs/docs/reference/command-line-interface.md
  integration/example-library/meltano-objects/index.md
  src/meltano/cli/add.py
  src/meltano/cli/remove.py
  src/meltano/cli/utils.py
  tests/meltano/cli/test_remove.py
Labels: cli, plugin management

#9352 docs: Improve reference description of `settings[*].aliases` and `settings[*].env`
  docs/docs/reference/plugin-definition-syntax.md
Labels: Documentation, plugin management, Settings

#9353 feat: Accept JSON string to configure the GCS state backend
  docs/docs/concepts/state_backends.md
  docs/docs/reference/settings.mdx
  pyproject.toml
  src/meltano/core/state_store/google.py
  tests/meltano/core/state_store/test_filesystem.py
Labels: State Management

#9355 refactor: Make generic error message more log-friendly
  src/meltano/cli/__init__.py
  src/meltano/cli/utils.py
Labels: cli, Logging

#9357 packaging: Allow boto3 1.39.x
  pyproject.toml
  uv.lock
Labels: dependencies, State Management

#9364 refactor: Replace `atomicwrites` with stdlib functions
  pyproject.toml
  src/meltano/core/project_files.py
  uv.lock
Labels: dependencies

#9365 revert: Revert unusable `utc` log formatter parameter
  .git-blame-ignore-revs
  docs/docs/guide/logging.md
  src/meltano/core/logging/formatters.py
  tests/meltano/core/logging/test_formatters.py
Labels: kind/Bug, Logging

#9377 ci: Update reusable workflows
  .github/actions/docker-build-scan-push/action.yml
Labels: CI/CD

#9370 docs: The "most straightforward" way to install Meltano now is uv
  docs/docs/guide/production.md
Labels: Documentation, installation

#9366 feat: Use `NO_UTC=1` environment variable to emit logs with timestamps in your local timezone
  docs/docs/reference/command-line-interface.md
  src/meltano/core/logging/formatters.py
  src/meltano/core/logging/output_logger.py
  src/meltano/core/logging/utils.py
  tests/fixtures/core.py
  tests/meltano/core/logging/test_formatters.py
Labels: Logging

#9374 feat: Add decimal setting kind
  docs/docs/guide/plugin-management.md
  docs/docs/reference/plugin-definition-syntax.md
  integration/example-library/meltano-config/ending-meltano.yml
  integration/example-library/meltano-config/index.md
  src/meltano/core/setting_definition.py
  src/meltano/core/yaml.py
  src/meltano/schemas/meltano.schema.json
  tests/meltano/core/test_setting_definition.py
  tests/meltano/core/test_yaml.py
Labels: Community-Contributed PR

#9388 refactor: Remove dependency on croniter
  pyproject.toml
  src/meltano/cli/schedule.py
  src/meltano/core/schedule.py
  src/meltano/core/schedule_service.py
  tests/meltano/core/test_schedule_service.py
  uv.lock
Labels: dependencies

#9386 fix: support both .yaml and .yml extensions for logging config files
  docs/docs/guide/logging.md
  docs/docs/reference/settings.mdx
  src/meltano/core/logging/utils.py
  tests/meltano/core/logging/test_logging_utils.py
Labels: Community-Contributed PR, Logging

#9401 docs(core): Fix typo in `meltano --version` example
  docs/docs/getting-started/part1.mdx
Labels: Community-Contributed PR

#9394 fix: Recreate venv when plugin Python version is changed
  src/meltano/core/venv_service.py
  tests/meltano/core/test_venv_service.py
Labels: Community-Contributed PR, plugin management

#9417 test: Improve coverage measurement with `patch = "subprocess"`
  noxfile.py
  pyproject.toml
  uv.lock
Labels: CI/CD, dependencies

#9410 docs: Document PostgreSQL database privileges and requirements
  docs/docs/reference/settings.mdx
Labels: Documentation
