Repository meltano/meltano, pull requests merged in 2025-04, with the labels that each got.

#9191 docs: Drop dbt version pin required by now fixed dbt-labs/dbt-postgres#96
  docs/docs/getting-started/part3.mdx
Labels: Community-Contributed PR

#9200 fix: Display a more useful error message if an unknown plugin could be a custom one
  src/meltano/core/plugin/project_plugin.py
  src/meltano/core/project_plugins_service.py
Labels: cli, plugin management

#9208 fix: Use `config generate` command to generate `airflow.cfg` configuration file
  src/meltano/core/plugin/airflow.py
  tests/meltano/core/plugin/test_airflow.py
Labels: Community-Contributed PR

#9222 fix: Make `name` argument of setting definition required
  src/meltano/core/setting_definition.py
  tests/meltano/core/test_setting_definition.py
Labels: Settings

#9193 fix: Omit warning log messages coming from `urllib3` certificate errors
  src/meltano/core/logging/utils.py
Labels: Logging

#9235 packaging: Allow installing Meltano with boto 1.38
  pyproject.toml
  uv.lock
Labels: dependencies
