Repository meltano/meltano, pull requests merged in 2025-03, with the labels that each got.

#8994 chore: Use Poetry 2
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: flow::blocked, dependencies

#9139 packaging: Switch to uv 🚀
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/docker_publish.yml
  .github/workflows/integration_tests.yml
  .github/workflows/resources/constraints.txt
  .github/workflows/test.yml
  .pre-commit-config.yaml
  docs/docs/contribute/prerequisites.md
  docs/docs/contribute/style.md
  noxfile.py
  poetry.lock
  pyproject.toml
  tests/meltano/core/plugin/singer/test_tap.py
  tests/meltano/core/test_meltano_invoker.py
  tests/meltano/core/test_plugin_install_service.py
  uv.lock
Labels: dependencies

#9119 feat: Parse relative dates in plugin config
  docs/docs/reference/plugin-definition-syntax.md
  integration/example-library/meltano-run-merge-states/index.md
  integration/meltano-run-merge-states/validate.sh
  pyproject.toml
  src/meltano/core/setting_definition.py
  src/meltano/core/utils/__init__.py
  src/meltano/schemas/meltano.schema.json
  tests/meltano/core/test_setting_definition.py
  uv.lock
Labels: kind/Feature, Settings

#9158 feat: Pass project `env` to installation environment
  src/meltano/core/meltano_file.py
  src/meltano/core/plugin_install_service.py
Labels: installation

#9162 fix: Stringify YAML values from top-level `env` key of `meltano.yml`
  src/meltano/core/meltano_file.py
  tests/meltano/core/test_meltano_file.py
Labels: Settings

#9164 ci: Pin GitHub actions in reusable workflows
  .github/actions/docker-build-scan-push/action.yml
Labels: CI/CD, dependencies

#9176 refactor: Refactor `CatalogRule` classes into dataclasses
  src/meltano/core/plugin/singer/catalog.py
Labels: performance, kind/Tech Debt

#9179 docs: Added installation examples for additional Meltano components and clarify system database requirements
  docs/docs/guide/advanced-topics.md
Labels: Documentation, Community-Contributed PR
